name: Playwright Tests
on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    # Update env variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: next_ecommerce
      PGUSERNAME: next_ecommerce
      PGPASSWORD: next_ecommerce

    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER next_ecommerce PASSWORD 'next_ecommerce'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=next_ecommerce next_ecommerce
      - uses: actions/checkout@v2
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: yarn playwright install-deps
      - run: yarn migrate up
      - name: Build localhost
        run: yarn build
      - name: Run tests
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots-videos
          path: test-results/
